import * as React from 'react';
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import {
  createTheme,
  responsiveFontSizes,
  ThemeProvider,
} from '@mui/material/styles';
import Typography from '@mui/material/Typography';
import Main from './components/Main';

let theme = createTheme();
theme = responsiveFontSizes(theme);

export default function Home() {
  return (

    <div className={styles.container}>
      <ThemeProvider theme={theme}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Main />

      </ThemeProvider>
    </div>
  )
}
